### ISSUE TITLE
files not uploading

### ISSUE THREAD

**Issue by prasanth22** [harish81/digidocu#2]
"message": "Method Illuminate\\Validation\\Validator::validateFiles does not exist.",
    "exception": "BadMethodCallException",
    "file": "D:\\wamp64\\www\\digidocument\\vendor\\laravel\\framework\\src\\Illuminate\\Validation\\Validator.php",
    "line": 1197,

**Comment by harish81** [comment]
Thank you for trying DigiDocu, I'll inspect this bug, and try to fix it soon

**Comment by harish81** [comment]
Hi, @prasanth22 can you provide full stack-trace of errors, which helps us to inspect more.

**Comment by harish81** [comment]
Hi, @prasanth22  You have created invalid validation rule for File-Type. Check your rules in _**Settings>>FileTypes**_. (The validation  must be valid laravel rules like:

> required|mimes:jpeg,bmp

) See: https://laravel.com/docs/6.x/validation#available-validation-rules

**Comment by harish81** [comment]
@prasanth22 you have created **files** validation rules which is invalid.
