### ISSUE TITLE
System installation failures in laravel 8 even after the downgrade.

### ISSUE THREAD

**Issue by theefreelancer** [harish81/digidocu#27]
Below is the code snippet.
PHP Warning:  require(/opt/lampp/htdocs/Projects/digidocu/vendor/composer/../../tests/Database/stubs/MigrationCreatorFakeMigration.php): Failed to open stream: No such file or directory in /opt/lampp/htdocs/Projects/digidocu/vendor/composer/autoload_real.php on line 53
PHP Fatal error:  Uncaught Error: Failed opening required '/opt/lampp/htdocs/Projects/digidocu/vendor/composer/../../tests/Database/stubs/MigrationCreatorFakeMigration.php' (include_path='.:/usr/share/php') in /opt/lampp/htdocs/Projects/digidocu/vendor/composer/autoload_real.php:53
Stack trace:
#0 /opt/lampp/htdocs/Projects/digidocu/vendor/composer/autoload_real.php(36): composerRequire636fc3f4144d3af8a3fe0337b136f7ab()
#1 /opt/lampp/htdocs/Projects/digidocu/vendor/autoload.php(12): ComposerAutoloaderInit636fc3f4144d3af8a3fe0337b136f7ab::getLoader()
#2 /opt/lampp/htdocs/Projects/digidocu/artisan(18): require('...')
#3 {main}
  thrown in /opt/lampp/htdocs/Projects/digidocu/vendor/composer/autoload_real.php on line 53
I tried to change to the auto the auto load file as well to accomodate the files as listed here
"autoload": {
        "files": [
         
            "app/Helpers/helpers.php"
        ],
Here is my JSON file 
{
    "name": "laravel/framework",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "homepage": "https://laravel.com",
    "support": {
        "issues": "https://github.com/laravel/framework/issues",
        "source": "https://github.com/laravel/framework"
    },
    "authors": [
        {
            "name": "Taylor Otwell",
            "email": "taylor@laravel.com"
        }
    ],
    "require": {
        "php": "^8.0.2",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "doctrine/inflector": "^2.0",
        "dragonmantank/cron-expression": "^3.1",
        "egulias/email-validator": "^3.1",
        "fruitcake/php-cors": "^1.2",
        "laravel/serializable-closure": "^1.0",
        "league/commonmark": "^2.2",
        "league/flysystem": "^3.0.16",
        "monolog/monolog": "^2.0",
        "nesbot/carbon": "^2.53.1",
        "nunomaduro/termwind": "^1.13",
        "psr/container": "^1.1.1|^2.0.1",
        "psr/log": "^1.0|^2.0|^3.0",
        "psr/simple-cache": "^1.0|^2.0|^3.0",
        "ramsey/uuid": "^4.2.2",
        "symfony/console": "^6.0.3",
        "symfony/error-handler": "^6.0",
        "symfony/finder": "^6.0",
        "symfony/http-foundation": "^6.0",
        "symfony/http-kernel": "^6.0",
        "symfony/mailer": "^6.0",
        "symfony/mime": "^6.0",
        "symfony/process": "^6.0",
        "symfony/routing": "^6.0",
        "symfony/var-dumper": "^6.0",
        "tijsverkoyen/css-to-inline-styles": "^2.2.2",
        "vlucas/phpdotenv": "^5.4.1",
        "voku/portable-ascii": "^2.0"
    },
    "replace": {
        "illuminate/auth": "self.version",
        "illuminate/broadcasting": "self.version",
        "illuminate/bus": "self.version",
        "illuminate/cache": "self.version",
        "illuminate/collections": "self.version",
        "illuminate/conditionable": "self.version",
        "illuminate/config": "self.version",
        "illuminate/console": "self.version",
        "illuminate/container": "self.version",
        "illuminate/contracts": "self.version",
        "illuminate/cookie": "self.version",
        "illuminate/database": "self.version",
        "illuminate/encryption": "self.version",
        "illuminate/events": "self.version",
        "illuminate/filesystem": "self.version",
        "illuminate/hashing": "self.version",
        "illuminate/http": "self.version",
        "illuminate/log": "self.version",
        "illuminate/macroable": "self.version",
        "illuminate/mail": "self.version",
        "illuminate/notifications": "self.version",
        "illuminate/pagination": "self.version",
        "illuminate/pipeline": "self.version",
        "illuminate/queue": "self.version",
        "illuminate/redis": "self.version",
        "illuminate/routing": "self.version",
        "illuminate/session": "self.version",
        "illuminate/support": "self.version",
        "illuminate/testing": "self.version",
        "illuminate/translation": "self.version",
        "illuminate/validation": "self.version",
        "illuminate/view": "self.version"
    },
    "require-dev": {
        "aws/aws-sdk-php": "^3.198.1",
        "doctrine/dbal": "^2.13.3|^3.1.4",
        "fakerphp/faker": "^1.9.2",
        "guzzlehttp/guzzle": "^7.2",
        "league/flysystem-aws-s3-v3": "^3.0",
        "league/flysystem-ftp": "^3.0",
        "league/flysystem-sftp-v3": "^3.0",
        "mockery/mockery": "^1.4.4",
        "orchestra/testbench-core": "^7.1",
        "pda/pheanstalk": "^4.0",
        "phpstan/phpstan": "^1.4.7",
        "phpunit/phpunit": "^9.5.8",
        "predis/predis": "^1.1.9|^2.0",
        "symfony/cache": "^6.0"
    },
    "provide": {
        "psr/container-implementation": "1.1|2.0",
        "psr/simple-cache-implementation": "1.0|2.0|3.0"
    },
    "conflict": {
        "tightenco/collect": "<5.5.33"
    },
    "autoload": {
        "files": [
         
            "app/Helpers/helpers.php"
        ],
        "psr-4": {
            "Illuminate\\": "src/Illuminate/",
            "Illuminate\\Support\\": [
                "src/Illuminate/Macroable/",
                "src/Illuminate/Collections/",
                "src/Illuminate/Conditionable/"
            ]
        }
    },
    "autoload-dev": {
        "files": [
            "tests/Database/stubs/MigrationCreatorFakeMigration.php"
        ],
        "psr-4": {
            "Illuminate\\Tests\\": "tests/"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "9.x-dev"
        }
    },
    "suggest": {
        "ext-bcmath": "Required to use the multiple_of validation rule.",
        "ext-ftp": "Required to use the Flysystem FTP driver.",
        "ext-gd": "Required to use Illuminate\\Http\\Testing\\FileFactory::image().",
        "ext-memcached": "Required to use the memcache cache driver.",
        "ext-pcntl": "Required to use all features of the queue worker.",
        "ext-posix": "Required to use all features of the queue worker.",
        "ext-redis": "Required to use the Redis cache and queue drivers (^4.0|^5.0).",
        "ably/ably-php": "Required to use the Ably broadcast driver (^1.0).",
        "aws/aws-sdk-php": "Required to use the SQS queue driver, DynamoDb failed job storage, and SES mail driver (^3.198.1).",
        "brianium/paratest": "Required to run tests in parallel (^6.0).",
        "doctrine/dbal": "Required to rename columns and drop SQLite columns (^2.13.3|^3.1.4).",
        "fakerphp/faker": "Required to use the eloquent factory builder (^1.9.1).",
        "filp/whoops": "Required for friendly error pages in development (^2.14.3).",
        "guzzlehttp/guzzle": "Required to use the HTTP Client and the ping methods on schedules (^7.2).",
        "laravel/tinker": "Required to use the tinker console command (^2.0).",
        "league/flysystem-aws-s3-v3": "Required to use the Flysystem S3 driver (^3.0).",
        "league/flysystem-ftp": "Required to use the Flysystem FTP driver (^3.0).",
        "league/flysystem-sftp-v3": "Required to use the Flysystem SFTP driver (^3.0).",
        "mockery/mockery": "Required to use mocking (^1.4.4).",
        "nyholm/psr7": "Required to use PSR-7 bridging features (^1.2).",
        "pda/pheanstalk": "Required to use the beanstalk queue driver (^4.0).",
        "phpunit/phpunit": "Required to use assertions and run tests (^9.5.8).",
        "predis/predis": "Required to use the predis connector (^1.1.9|^2.0).",
        "psr/http-message": "Required to allow Storage::put to accept a StreamInterface (^1.0).",
        "pusher/pusher-php-server": "Required to use the Pusher broadcast driver (^6.0|^7.0).",
        "symfony/cache": "Required to PSR-6 cache bridge (^6.0).",
        "symfony/filesystem": "Required to enable support for relative symbolic links (^6.0).",
        "symfony/http-client": "Required to enable support for the Symfony API mail transports (^6.0).",
        "symfony/mailgun-mailer": "Required to enable support for the Mailgun mail transport (^6.0).",
        "symfony/postmark-mailer": "Required to enable support for the Postmark mail transport (^6.0).",
        "symfony/psr-http-message-bridge": "Required to use PSR-7 bridging features (^2.0)."
    },
    "config": {
        "sort-packages": true,
        "allow-plugins": {
            "composer/package-versions-deprecated": true
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
Its pretty long but i really a debug for this
PS: My terminal is using php version 8.1.9
       Laravel version 9

**Comment by harish81** [comment]
Are you sure have installed composer dependencies @theefreelancer ?
