### ISSUE TITLE
how can i display new document in first page .

### ISSUE THREAD

**Issue by Quakyla** [harish81/digidocu#5]
Hi Harish !
My project display new document in last page ..
can you tell me how can i display new document in first page .
thanks so much !

**Comment by ada27** [comment]
maybe this can help you
You can add orderbyDesc in app Repositories DocumentRepositories.php

![image](https://user-images.githubusercontent.com/44355293/87623207-778c7f80-c757-11ea-9ee6-9e3514310deb.png)

hopefully can help you

**Comment by Quakyla** [comment]
This tips work well.T
thanks so much for quickly support !
J.,
