### ISSUE TITLE
create document route issue

### ISSUE THREAD

**Issue by CesarCalheiro** [harish81/digidocu#7]
I have checked that the router for create document , do not existed 
to upload the document, i tried to figure out and understand the code to fix it out.

<script>
        function gotoUpload() {
            var docId = $("#document_id").val();
            var urlToUp = "{{route('documents.files.create', '')}}"+"/"+docId;
            console.log(urlToUp);
            window.location.href = urlToUp;
            return false;
        }

========================https://github.com/harish81/digidocu/blob/master/app/Http/Controllers/DocumentController.php  ======================

  public function create()
    {
        $this->authorize('create', Document::class);
        $tags = $this->tagRepository->all();
        $customFields = $this->customFieldRepository->getForModel('documents');
        return view('documents.create', compact('tags', 'customFields'));
    }

========================================================
https://github.com/harish81/digidocu/blob/master/routes/web.php

==========================================================

**Comment by harish81** [comment]
Hello Mr. @CesarCalheiro, the `document.files.create` route exists and valid and it is working fine.
Please make sure you test things and post error log or screenshot.

**Comment by kingqabil** [comment]
hi when i try to upload a file in the document iam geting error please help me 
![SharedScreenshot](https://user-images.githubusercontent.com/20561465/105615278-6b593d00-5de0-11eb-8fce-83e79c5074ad.jpg)

**Comment by CesarCalheiro** [comment]
Hello @Harish Nandoliya problem fixed, thank you for your attention
